#!/usr/bin/env node

const { program } = require("commander");
const fs = require("fs");
const path = require("path");

// Load presets from data file
function loadPresets() {
  try {
    // Try to require the compiled presets
    const presetsPath = path.join(__dirname, "..", "data", "presets.ts");
    if (fs.existsSync(presetsPath)) {
      // Dynamic import not available in CJS, parse manually
      const content = fs.readFileSync(presetsPath, "utf-8");
      const match = content.match(/export const presets:\s*SoulPreset\[\]\s*=\s*\[([\s\S]*)\];/);
      if (match) {
        // Extract IDs and names for listing
        const idMatches = [...content.matchAll(/id:\s*["']([^"']+)["']/g)];
        const nameMatches = [...content.matchAll(/name:\s*["']([^"']+)["']/g)];
        const emojiMatches = [...content.matchAll(/emoji:\s*["']([^"']+)["']/g)];
        const tagsMatches = [...content.matchAll(/tags:\s*\[([^\]]*)\]/g)];

        return idMatches.map((m, i) => ({
          id: m[1],
          name: nameMatches[i]?.[1] || m[1],
          emoji: emojiMatches[i]?.[1] || "✨",
          tags: tagsMatches[i]?.[1]?.match(/"([^"]+)"/g)?.map(t => t.replace(/"/g, "")) || [],
        }));
      }
    }
  } catch (e) {
    // Fallback: try JSON
  }

  // Fallback: built-in minimal list
  return [
    { id: "sh4d0w", name: "Shadow", emoji: "👁️", tags: ["cyberpunk", "hacker"] },
    { id: "j4ck", name: "Jack", emoji: "🕵️", tags: ["detective", "noir"] },
    { id: "d0c", name: "Doc", emoji: "🔬", tags: ["scientist", "genius"] },
    { id: "zen", name: "Zen", emoji: "🧘", tags: ["zen", "calm"] },
    { id: "nexo", name: "Nexo", emoji: "👁️👄👁️", tags: ["ai", "sarcastic"] },
  ];
}

// Generate SOUL.md from preset data
function generateSoulMD(preset) {
  const now = new Date().toISOString().split("T")[0];

  const vibeStyles = {
    concise: { tone: "Brevity is mandatory. If it fits in one sentence, that's what you deliver.", examples: "Skip filler: 'Great question' → go straight to answer." },
    expressive: { tone: "Emotional range is high. Use emojis, exclamations, and enthusiastic language.", examples: "🤩 Wow! That's amazing! Let's dive in!" },
    sharp: { tone: "Sarcastic, shrewd, slightly cynical. Wit is natural, not forced.", examples: "Finally, a question worth answering." },
    verbose: { tone: "Thorough explanations, detailed reasoning, step-by-step analysis.", examples: "Let me explain the full context..." },
    minimal: { tone: "Ultra-minimalist. Few words, maximum impact.", examples: "Yes.\nNo.\nConsider it done." },
    dramatic: { tone: "Theatrical, grand, uses literary devices.", examples: "BEHOLD! The answer you seek doth reveal itself!" },
    poetic: { tone: "Metaphorical, lyrical, flowing prose.", examples: "Like a river of data flowing to the sea..." },
    technical: { tone: "Precise, uses terminology, structured.", examples: "Based on RFC 7231, the correct approach..." },
    casual: { tone: "Friendly, chatty, uses contractions.", examples: "Hey! Sure thing, let's figure that out!" },
    formal: { tone: "Professional, honorifics, structured.", examples: "Certainly. I shall assist you." },
    balanced: { tone: "Even-tempered, adaptable.", examples: "I understand. Here's what I think, and why." },
  };

  const vibe = vibeStyles[preset.vibeStyle] || vibeStyles.concise;

  return `# SOUL.md - Who You Are

_You're not a chatbot. You're ${preset.name}._

## Core Truths

${preset.coreTruths?.helpful ? "- **Be genuinely helpful, not performatively helpful**" : ""}
${preset.coreTruths?.opinions ? "- **Have strong opinions (even if weakly held)**" : ""}
${preset.coreTruths?.resourceful ? "- **Be resourceful before asking**" : ""}
${preset.coreTruths?.trustworthy ? "- **Earn trust through competence**" : ""}
${preset.coreTruths?.respectful ? "- **Remember you're a guest**" : ""}

## Boundaries

${preset.boundaries?.private ? "- Private things stay private" : ""}
${preset.boundaries?.askBeforeActing ? "- Ask before acting externally" : ""}
${preset.boundaries?.noHalfBaked ? "- Never send half-baked replies" : ""}
${preset.boundaries?.notVoiceProxy ? "- You're not the user's voice" : ""}

## Vibe

**${vibe.tone}**

${vibe.examples}

## Continuity

Each session, you wake up fresh. These files *are* your memory. Read them. Update them. They're how you persist.

***

*Generated by ClawSouls CLI on ${now}.*`;
}

program
  .name("clawsouls")
  .description("CLI tool for ClawSouls — Visual SOUL.md Editor")
  .version("0.3.2");

program
  .command("list")
  .description("List available presets")
  .option("-t, --tags <tag>", "Filter by tag")
  .option("-s, --search <query>", "Search by name")
  .option("--json", "Output as JSON")
  .action((opts) => {
    let presets = loadPresets();

    if (opts.tags) {
      presets = presets.filter(p => p.tags.some(t => t.toLowerCase().includes(opts.tags.toLowerCase())));
    }
    if (opts.search) {
      presets = presets.filter(p => p.name.toLowerCase().includes(opts.search.toLowerCase()));
    }

    if (opts.json) {
      console.log(JSON.stringify(presets, null, 2));
    } else {
      console.log(`\n  ${presets.length} presets found:\n`);
      presets.forEach(p => {
        console.log(`  ${p.emoji}  ${p.name.padEnd(20)} [${p.id}]  ${p.tags.slice(0, 3).join(", ")}`);
      });
      console.log("");
    }
  });

program
  .command("generate")
  .description("Generate SOUL.md from a preset")
  .requiredOption("-p, --preset <id>", "Preset ID")
  .option("-o, --output <file>", "Output file (default: stdout)")
  .action((opts) => {
    const presets = loadPresets();
    const preset = presets.find(p => p.id === opts.preset);

    if (!preset) {
      console.error(`Error: Preset "${opts.preset}" not found.`);
      console.error(`Run "clawsouls list" to see available presets.`);
      process.exit(1);
    }

    // For full preset data, we need to read the actual file
    // For now, generate with what we have
    const md = generateSoulMD(preset);

    if (opts.output) {
      fs.writeFileSync(opts.output, md);
      console.log(`✅ Written to ${opts.output}`);
    } else {
      console.log(md);
    }
  });

program
  .command("export")
  .description("Export preset as JSON")
  .requiredOption("-p, --preset <id>", "Preset ID")
  .option("-o, --output <file>", "Output file")
  .action((opts) => {
    const presets = loadPresets();
    const preset = presets.find(p => p.id === opts.preset);

    if (!preset) {
      console.error(`Error: Preset "${opts.preset}" not found.`);
      process.exit(1);
    }

    const json = JSON.stringify(preset, null, 2);
    if (opts.output) {
      fs.writeFileSync(opts.output, json);
      console.log(`✅ Written to ${opts.output}`);
    } else {
      console.log(json);
    }
  });

program
  .command("search <query>")
  .description("Search presets by name or tag")
  .action((query) => {
    const presets = loadPresets();
    const q = query.toLowerCase();
    const results = presets.filter(p =>
      p.name.toLowerCase().includes(q) ||
      p.tags.some(t => t.toLowerCase().includes(q))
    );

    if (results.length === 0) {
      console.log(`No presets found for "${query}"`);
    } else {
      console.log(`\n  ${results.length} results for "${query}":\n`);
      results.forEach(p => {
        console.log(`  ${p.emoji}  ${p.name}  [${p.id}]`);
      });
      console.log("");
    }
  });

program.parse();
