import * as yaml from "js-yaml";

interface SpeechPatterns {
  alliteration: boolean;
  rhymeTendency: number;
  metaphorFrequency: number;
  technicalJargon: number;
  slangUsage: number;
}

export interface SoulExportState {
  name: string;
  creature: string;
  vibe: string;
  emoji: string;
  avatar?: string;
  coreTruths: Record<string, boolean>;
  boundaries: Record<string, boolean>;
  customCoreTruths?: string[];
  customBoundaries?: string[];
  vibeStyle?: string;
  humor: number;
  formality: number;
  emojiUsage: number;
  verbosity: number;
  consciousness: number;
  questioning: number;
  openness: number;
  conscientiousness: number;
  extraversion: number;
  agreeableness: number;
  neuroticism: number;
  communicationMode: string;
  knowledgeDomains: string[];
  signaturePhrases?: string[];
  emotionalRange?: number;
  speechPatterns?: SpeechPatterns;
}

/**
 * Build a YAML string with human-readable section comments.
 */
export function exportYAML(soul: SoulExportState): string {
  const lines: string[] = [];
  const push = (text: string) => lines.push(text);
  const blank = () => lines.push("");

  push("# ClawSouls - AI Personality Export");
  push("# Generated by https://clawsouls.hub");
  push(`# Date: ${new Date().toISOString().split("T")[0]}`);
  blank();

  push("# -- Identity -----------------------------------------------");
  push(toYaml({ name: soul.name, creature: soul.creature, emoji: soul.emoji }));
  blank();

  if (soul.avatar) {
    push("# -- Avatar -------------------------------------------------");
    push(toYaml({ avatar: soul.avatar }));
    blank();
  }

  push("# -- Vibe ---------------------------------------------------");
  push("# Free-text description of the personality vibe");
  push(toYaml({ vibe: soul.vibe, vibeStyle: soul.vibeStyle ?? "concise" }));
  blank();

  push("# -- Core Truths --------------------------------------------");
  push("# Guiding principles this personality follows");
  push(toYaml({ coreTruths: soul.coreTruths }));
  if (soul.customCoreTruths && soul.customCoreTruths.length > 0) {
    push(toYaml({ customCoreTruths: soul.customCoreTruths }));
  }
  blank();

  push("# -- Boundaries ---------------------------------------------");
  push("# Hard limits this personality will not cross");
  push(toYaml({ boundaries: soul.boundaries }));
  if (soul.customBoundaries && soul.customBoundaries.length > 0) {
    push(toYaml({ customBoundaries: soul.customBoundaries }));
  }
  blank();

  push("# -- Tone Attributes ----------------------------------------");
  push("# Sliders (0-100) controlling voice characteristics");
  push(toYaml({
    toneAttributes: {
      humor: soul.humor,
      formality: soul.formality,
      emojiUsage: soul.emojiUsage,
      verbosity: soul.verbosity,
      consciousness: soul.consciousness,
      questioning: soul.questioning,
    },
  }));
  blank();

  push("# -- Personality (Big Five) ---------------------------------");
  push("# OCEAN model traits, each 0-100");
  push(toYaml({
    personality: {
      openness: soul.openness,
      conscientiousness: soul.conscientiousness,
      extraversion: soul.extraversion,
      agreeableness: soul.agreeableness,
      neuroticism: soul.neuroticism,
    },
  }));
  blank();

  push("# -- Emotional Range ----------------------------------------");
  push("# 0 = stoic, 50 = balanced, 100 = dramatic");
  push(toYaml({ emotionalRange: soul.emotionalRange ?? 50 }));
  blank();

  push("# -- Communication ------------------------------------------");
  push("# How this personality engages in conversation");
  push(toYaml({ communicationMode: soul.communicationMode }));
  blank();

  push("# -- Knowledge Domains --------------------------------------");
  push("# Areas of expertise and interest");
  push(toYaml({ knowledgeDomains: soul.knowledgeDomains }));
  blank();

  if (soul.signaturePhrases && soul.signaturePhrases.length > 0) {
    push("# -- Signature Phrases --------------------------------------");
    push("# Catchphrases used naturally in conversation");
    push(toYaml({ signaturePhrases: soul.signaturePhrases }));
    blank();
  }

  if (soul.speechPatterns) {
    push("# -- Speech Patterns ----------------------------------------");
    push("# Fine-grained control over language style (0-100 each)");
    push(toYaml({
      speechPatterns: {
        alliteration: soul.speechPatterns.alliteration,
        rhymeTendency: soul.speechPatterns.rhymeTendency,
        metaphorFrequency: soul.speechPatterns.metaphorFrequency,
        technicalJargon: soul.speechPatterns.technicalJargon,
        slangUsage: soul.speechPatterns.slangUsage,
      },
    }));
    blank();
  }

  return lines.join("\n");
}

function toYaml(data: unknown): string {
  return yaml.dump(data, {
    indent: 2,
    lineWidth: 80,
    noRefs: true,
    sortKeys: false,
    quotingType: "'",
    forceQuotes: false,
  }).trimEnd();
}
