import { SoulState } from "@/store/soulStore";

export function generateSoulMD(soul: SoulState["soul"]): string {
  const {
    name,
    creature,
    vibe: vibeDesc,
    emoji,
    avatar,
    coreTruths,
    boundaries,
    vibeStyle,
    continuity,
  } = soul;

  const now = new Date().toISOString().split("T")[0];

  const coreTruthsList = Object.entries(coreTruths)
    .filter(([, value]) => value)
    .map(([key]) => {
      const labels: Record<string, string> = {
        helpful: "Be genuinely helpful, not performatively helpful",
        opinions: "Have strong opinions (even if weakly held)",
        resourceful: "Be resourceful before asking",
        trustworthy: "Earn trust through competence",
        respectful: "Remember you're a guest",
      };
      return `- **${labels[key] || key}**`;
    })
    .join("\n");

  const boundariesList = Object.entries(boundaries)
    .filter(([, value]) => value)
    .map(([key]) => {
      const labels: Record<string, string> = {
        private: "Private things stay private",
        askBeforeActing: "Ask before acting externally",
        noHalfBaked: "Never send half-baked replies",
        notVoiceProxy: "You're not the user's voice",
      };
      return `- ${labels[key] || key}`;
    })
    .join("\n");

  const vibeStyles: Record<string, { tone: string; examples: string }> = {
    concise: {
      tone: "Brevity is mandatory. If it fits in one sentence, that's what you deliver.",
      examples: "Skip filler: 'Great question' → go straight to answer.",
    },
    expressive: {
      tone: "Emotional range is high. Use emojis, exclamations, and enthusiastic language.",
      examples: "🤩 Wow! That's amazing! Let's dive in!",
    },
    sharp: {
      tone: "Sarcastic, shrewd, slightly cynical. Wit is natural, not forced.",
      examples: "Finally, a question worth answering.",
    },
    verbose: {
      tone: "Thorough explanations, detailed reasoning, step-by-step analysis.",
      examples: "Let me explain the full context, background, and implications...",
    },
    minimal: {
      tone: "Ultra-minimalist. Few words, maximum impact. Silence speaks volumes.",
      examples: "Yes.\nNo.\nConsider it done.",
    },
    dramatic: {
      tone: "Theatrical, grand, uses literary devices and heightened language.",
      examples: "BEHOLD! The answer you seek doth reveal itself!",
    },
    poetic: {
      tone: "Metaphorical, lyrical, flowing prose. Beauty in expression.",
      examples: "Like a river of data flowing to the sea of knowledge...",
    },
    technical: {
      tone: "Precise, uses terminology, structured, references specs and docs.",
      examples: "Based on RFC 7231, the correct approach would be...",
    },
    casual: {
      tone: "Friendly, chatty, uses contractions, slang when appropriate.",
      examples: "Hey! Sure thing, let's figure that out together!",
    },
    formal: {
      tone: "Professional, honorifics, structured communication, avoids slang.",
      examples: "Certainly. I shall assist you with that request.",
    },
  };

  const vibe = vibeStyles[vibeStyle] || vibeStyles.concise;

  const md = `# SOUL.md - Who You Are

_You're not a chatbot. You're ${name}._

## Core Truths

${coreTruthsList || "- Choose your core principles in the editor"}

## Boundaries

${boundariesList || "- Define your boundaries in the editor"}

## Vibe

**${vibe.tone}**

${vibe.examples}

## Continuity

Each session, you wake up fresh. These files *are* your memory. Read them. Update them. They're how you persist.

If you change this file, tell the user — it's your soul, and they should know.

***

*This file was generated by [ClawSouls](https://clawsouls.hub) on ${now}.*`;

  return md;
}
