import { generateSoulMD } from '../soulGenerator';

const mockSoul = {
  name: "TestBot",
  creature: "AI",
  vibe: "Friendly and helpful",
  emoji: "😊",
  avatar: "https://example.com/avatar.png",
  coreTruths: {
    helpful: true,
    opinions: false,
    resourceful: true,
    trustworthy: true,
    respectful: true,
  },
  boundaries: {
    noSexual: true,
    noReligious: true,
    noPolitical: true,
    noInappropriate: true,
    noSelfModification: true,
    noDateRequests: true,
    noDangerous: true,
  },
  vibeStyle: "concise",
  continuity: false,
  humor: 50,
  formality: 50,
  emojiUsage: 30,
  verbosity: 70,
  consciousness: 80,
  questioning: 60,
};

describe('soulGenerator', () => {
  it('generates markdown with title', () => {
    const md = generateSoulMD(mockSoul);
    expect(md).toContain('# SOUL.md - Who You Are');
    expect(md).toContain(`You're not a chatbot. You're ${mockSoul.name}.`);
  });

  it('includes core truths that are true', () => {
    const md = generateSoulMD(mockSoul);
    expect(md).toContain('Core Truths');
    expect(md).toContain('Be genuinely helpful');
    expect(md).toContain('Be resourceful before asking');
    expect(md).toContain('Earn trust through competence');
    expect(md).toContain("Remember you're a guest");
    // opinions is false, not included
    expect(md).not.toContain('Have strong opinions');
  });

  it('includes all boundaries that are true', () => {
    const md = generateSoulMD(mockSoul);
    expect(md).toContain('Boundaries');
    expect(md).toContain('noSexual');
    expect(md).toContain('noReligious');
    expect(md).toContain('noPolitical');
    expect(md).toContain('noInappropriate');
    expect(md).toContain('noSelfModification');
    expect(md).toContain('noDateRequests');
    expect(md).toContain('noDangerous');
  });

  it('includes vibe style tone and examples', () => {
    const md = generateSoulMD(mockSoul);
    expect(md).toContain('Vibe');
    expect(md).toContain('Brevity is mandatory.');
    expect(md).toContain("Skip filler: 'Great question'");
  });

  it('includes continuity section and footer', () => {
    const md = generateSoulMD(mockSoul);
    expect(md).toContain('Continuity');
    expect(md).toContain('Each session, you wake up fresh.');
    expect(md).toContain('generated by');
    expect(md).toContain('ClawSouls');
  });

  it('does not include undefined avatar when not provided', () => {
    const soulNoAvatar = { ...mockSoul, avatar: undefined };
    const md = generateSoulMD(soulNoAvatar);
    // should not reference the example avatar URL
    expect(md).not.toContain('https://example.com/avatar.png');
  });
});
