import { generateSoulMD } from '../soulGenerator';

const mockSoul = {
  name: "TestBot",
  creature: "AI",
  vibe: "Friendly and helpful",
  emoji: "😊",
  avatar: "https://example.com/avatar.png",
  coreTruths: {
    helpful: true,
    opinions: false,
    resourceful: true,
    trustworthy: true,
    respectful: true,
  },
  boundaries: {
    private: true,
    askBeforeActing: true,
    noHalfBaked: true,
    notVoiceProxy: false,
  },
  customCoreTruths: [],
  customBoundaries: [],
  vibeStyle: "concise",
  continuity: false,
  humor: 50,
  formality: 50,
  emojiUsage: 30,
  verbosity: 70,
  consciousness: 80,
  questioning: 60,
  openness: 70,
  conscientiousness: 50,
  extraversion: 50,
  agreeableness: 50,
  neuroticism: 30,
};

describe('soulGenerator', () => {
  it('generates markdown with title', () => {
    const md = generateSoulMD(mockSoul);
    expect(md).toContain('# SOUL.md - Who You Are');
    expect(md).toContain(`You're not a chatbot. You're ${mockSoul.name}.`);
  });

  it('includes core truths that are true', () => {
    const md = generateSoulMD(mockSoul);
    expect(md).toContain('Core Truths');
    expect(md).toContain('Be genuinely helpful');
    expect(md).toContain('Be resourceful before asking');
    expect(md).toContain('Earn trust through competence');
    expect(md).toContain("Remember you're a guest");
    // opinions is false, not included
    expect(md).not.toContain('Have strong opinions');
  });

  it('includes enabled boundaries', () => {
    const md = generateSoulMD(mockSoul);
    expect(md).toContain('Boundaries');
    expect(md).toContain('Private things stay private');
    expect(md).toContain('Ask before acting externally');
    expect(md).toContain('Never send half-baked replies');
    // notVoiceProxy is false, should not appear
    expect(md).not.toContain("You're not the user's voice");
  });

  it('includes vibe style tone and examples', () => {
    const md = generateSoulMD(mockSoul);
    expect(md).toContain('Vibe');
    expect(md).toContain('Brevity is mandatory.');
    expect(md).toContain("Skip filler: 'Great question'");
  });

  it('includes Big Five personality traits', () => {
    const md = generateSoulMD(mockSoul);
    expect(md).toContain('Personality');
    expect(md).toContain('Openness');
    expect(md).toContain('Conscientiousness');
    expect(md).toContain('Extraversion');
    expect(md).toContain('Agreeableness');
    expect(md).toContain('Neuroticism');
  });

  it('includes tone attributes section', () => {
    const md = generateSoulMD(mockSoul);
    expect(md).toContain('Tone');
    expect(md).toContain('Humor');
    expect(md).toContain('Formality');
  });

  it('includes continuity section and footer', () => {
    const md = generateSoulMD(mockSoul);
    expect(md).toContain('Continuity');
    expect(md).toContain('Each session, you wake up fresh.');
    expect(md).toContain('generated by');
    expect(md).toContain('ClawSouls');
  });

  it('does not include undefined avatar when not provided', () => {
    const soulNoAvatar = { ...mockSoul, avatar: undefined };
    const md = generateSoulMD(soulNoAvatar);
    expect(md).not.toContain('https://example.com/avatar.png');
  });

  it('includes custom core truths', () => {
    const soulWithCustom = {
      ...mockSoul,
      customCoreTruths: ["Always challenge assumptions", "Think in first principles"],
    };
    const md = generateSoulMD(soulWithCustom);
    expect(md).toContain('Always challenge assumptions');
    expect(md).toContain('Think in first principles');
  });

  it('includes custom boundaries', () => {
    const soulWithCustom = {
      ...mockSoul,
      customBoundaries: ["Never mention training data"],
    };
    const md = generateSoulMD(soulWithCustom);
    expect(md).toContain('Never mention training data');
  });

  it('handles balanced vibe style', () => {
    const balancedSoul = { ...mockSoul, vibeStyle: "balanced" };
    const md = generateSoulMD(balancedSoul);
    expect(md).toContain('Vibe');
    expect(md).toContain('Balanced');
  });
});
