/**
 * Script que escaneia public/avatars/ e gera lib/avatars.generated.ts
 * Uso: node scripts/scan-avatars.mjs
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const avatarsDir = path.resolve(__dirname, "../public/avatars");
const outputFile = path.resolve(__dirname, "../lib/avatars.generated.ts");

const files = fs.readdirSync(avatarsDir);
const names = files
  .filter((f) => f.endsWith(".png"))
  .map((f) => f.replace(/\.png$/, ""))
  .sort();

const content = `// GENERATED by scripts/scan-avatars.mjs — DO NOT EDIT MANUALLY
// Re-run: npm run scan-avatars

export const KNOWN_AVATARS: ReadonlySet<string> = new Set([
${names.map((n) => `  "${n}",`).join("\n")}
]);

export const AVATAR_COUNT = ${names.length};
`;

fs.writeFileSync(outputFile, content, "utf-8");
console.log(`✓ Generated ${outputFile} — ${names.length} avatars`);
